# This is a basic workflow to help you get started with Actions

name: Javadoc

# Controls when the action will run.
on:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  javadoc:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Generate Javadocs
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2025-24.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # Runs a single command using the runners shell
    - name: Create Javadocs
      run: ./gradlew javadoc
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build/docs/javadoc'
    - name: Deploy to Github Pages
      id: deployment
      uses: actions/deploy-pages@v1
