---
name: Check for Vendor Dependencies

# Controls when the action will run.
on:
  workflow_call:
    inputs:
      base_branch:
        type: string
        default: main
      version:
        type: string
        default: main

permissions:
  packages: read
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  vendor-update-check:
    name: Check for Vendor Updates
    runs-on: ubuntu-latest
    container: ghcr.io/frc5572/workflows/vendor-update:${{ inputs.version }}
    steps:      
      - name: Update Git
        run: |
          apk update && apk add git --update-cache
      - name: Generate a token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.VENDOR_UPDATE_APP_ID }}
          private-key: ${{ secrets.VENDOR_UPDATE_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Setup GIT
        run: |
          git config --system --add safe.directory "*"
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ env.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Run Update check
        run: |
          python /app/vendor-update.py
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          BASE_BRANCH: ${{ inputs.base_branch }}
          REPO_PATH: ${{ github.repository }}