---
name: Check for Vendor Dependencies

# Controls when the action will run.
on:
  workflow_call:
    inputs:
      base_branch:
        required: true
        type: string
        default: main
      version:
        required: true
        type: string
        default: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  vendor-update-check:
    name: Linting
    runs-on: ubuntu-latest
    container: ghcr.io/Frc5572/Worflows/vendor-update:${{ inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Update check
        run: python /app/vendor-update.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: ${{ inputs.base_branch }}
          REPO_PATH: ${{ github.repository }}